### ISSUE TITLE
trouble running examples/video_annotation.py

### ISSUE THREAD

**Issue by allenleetc** [kevinyamauchi/PointAnnotator#2]
Hi,
Was just browsing this demo and got a trace running the code in examples/video_annotation.py in ipython. Apologies if I am doing something silly! Any info appreciated.

* Ubuntu 18.04
* Installed napari in a new conda environment using pip per https://napari.org/, "from pip"
* Installed PointAnnotator (in conda env) via pip install -r REQUIREMENTS.txt 
* ipython --gui=qt
* manually ran code in examples/video_annotation.py
* trace:

```
/dat0/anaconda3/envs/napari-env/lib/python3.8/site-packages/magicgui/function_gui.py:283: FutureWarning: 

Creating a widget instance with `my_function.Gui()` is deprecated,
the magicgui decorator now returns a widget instance directly, so you
should simply use the function itself as a magicgui widget, or call
`my_function.show(run=True)` to run the application.
In a future version, the `Gui` attribute will be removed.

  warnings.warn(
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/dat0/anaconda3/envs/napari-env/lib/python3.8/site-packages/napari/_qt/event_loop.py", line 79, in gui_qt
    yield app
  File "/dat0/git/PointAnnotator/pointannotator/gui.py", line 91, in point_annotator
    viewer.window.add_dock_widget(label_menu)
  File "/dat0/anaconda3/envs/napari-env/lib/python3.8/site-packages/napari/_qt/qt_main_window.py", line 565, in add_dock_widget
    dock_widget = QtViewerDockWidget(
  File "/dat0/anaconda3/envs/napari-env/lib/python3.8/site-packages/napari/_qt/widgets/qt_viewer_dock_widget.py", line 82, in __init__
    self.widget = combine_widgets(
  File "/dat0/anaconda3/envs/napari-env/lib/python3.8/site-packages/napari/_qt/utils.py", line 187, in combine_widgets
    raise TypeError('"widget" must be a QWidget or a sequence of QWidgets')
TypeError: "widget" must be a QWidget or a sequence of QWidgets
```

**Comment by kevinyamauchi** [comment]
Hello @allenleetc ! I am sorry for the late reply and that you ran into this issue. My guess is this is due to one of the 0.2 series of updates to `magicgui` (pretty big refactor). I will take a look now and see if I can update the code to match the new magicgui API. In the meantime, if you roll back to `napari==0.4.1` and `magicgui==0.1.6`, it might work. Hopefully I can fix this example today!

**Comment by kevinyamauchi** [comment]
Hey @allenleetc ! Sorry again for the delay. I've merged a fix that should work with the new magicgui API (#3 ). I will close the issue, but please feel free to re-open/make another if you run into other problems! Thank you for bringing this to my attention.

**Comment by allenleetc** [comment]
@kevinyamauchi thanks your fix worked for me! Cool demo, thank you!
